-- 카테고리 별 도서 판매량 집계하기 
-- 2022년 1월의 카테고리 별 도서 판매량을 합산하고
-- 카테고리(CATEGORY), 총 판매량(TOTAL_SALES) 리스트를 출력
-- 결과는 카테고리명을 기준으로 오름차순 정렬

/* SELECT CATEGORY, SUM(TOTAL_SALES)
FROM BOOK, BOOK_SALES */

SELECT CATEGORY, SUM(SALES) TOTAL_SALES
FROM BOOK B, BOOK_SALES S
WHERE B.BOOK_ID = S.BOOK_ID AND
SALES_DATE LIKE "2022-01%"
GROUP BY CATEGORY
ORDER BY CATEGORY


/* WHERE B.BOOK_ID = S.BOOK_ID AND
SALES_DATE LIKE "2022-01%"
항상 이 구간을 빨리 생각하기가 어렵다. 연습 많이 하자  */